openapi: 3.0.1
info:
  title: mock
  version: '1.0'
servers:
  - url: https://sam-apim-cnn3-int.azure-api.cn/demo
paths:
  /demo:
    get:
      summary: test
      operationId: test
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                isTrusted: true
  /clone-68c11/demo:
    get:
      summary: test_v3
      operationId: 68c1182da86e2e39b9a2dee2
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                isTrusted: true
  /invoiceAPI/v1/open-order:
    get:
      summary: invoiceapi
      operationId: invoiceapi
      responses:
        '200':
          description: ''
  /access_token:
    post:
      summary: webeam_aessc-token
      operationId: webeam-aessc-token
      responses:
        '200':
          description: ''
  /m2m:
    post:
      summary: webeam_aessc-token-inbound
      operationId: 68c146f44127ec175b0242c5
      responses:
        '200':
          description: ''
  /mq:
    get:
      summary: MQ Demo
      operationId: mq-demo
      responses:
        '200':
          description: ''
  /healthcheck:
    get:
      summary: healthcheck
      operationId: healthcheck
      responses:
        '200':
          description: ''
  /xmltojson/test:
    post:
      summary: xmltojson
      operationId: 69038e8e7f62dce31f2d16c2
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                isTrusted: true
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]