openapi: 3.0.1
info:
  title: testapicreate089
  description: test api create
  version: '1.0'
servers:
  - url: https://sam-apim-cnn3-int.azure-api.cn/createapimock1
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]