openapi: 3.0.1
info:
  title: demo3
  version: v2
servers:
  - url: https://sam-apim-cnn3-int.azure-api.cn/demo3/v2
paths:
  /test:
    get:
      summary: test
      operationId: test
      responses:
        '200':
          description: ''
  /testconnection:
    get:
      summary: connection
      operationId: connection
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]