openapi: 3.0.1
info:
  title: test
  description: ''
  version: '1.0'
servers:
  - url: https://apimyyj.azure-api.net
paths:
  /gettest:
    get:
      summary: get
      description: get
      operationId: get
      responses:
        '202':
          description: ''
  /clone-69b3b/gettest:
    get:
      summary: get (clone)
      description: get
      operationId: 69b3b8365882a4a9e5893e00
      responses:
        '202':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]