openapi: 3.0.1
info:
  title: Demo-Client-Id
  version: '1.0'
servers:
  - url: https://sam-apim-cnn3-int.azure-api.cn/v1/demo/client/test
paths:
  /client/id/health/check:
    get:
      summary: Health Check
      operationId: health-check
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]