openapi: 3.0.1
info:
  title: GCDM
  version: '1.0'
servers:
  - url: https://sam-apim-cnn3-int.azure-api.cn/gcdm
paths:
  /v1/oauth/authenticate:
    post:
      summary: gcdm authenticate
      operationId: step1
      responses:
        '200':
          description: ''
  /clone-68b56/v1/oauth/authenticate:
    post:
      summary: step1 - get token id
      operationId: 68b564419062174627f46f17
      responses:
        '200':
          description: ''
  /v1/oauth/token:
    post:
      summary: gcdm get access token
      operationId: 68b821778537f358264ec750
      responses:
        '200':
          description: ''
  /tokencache:
    get:
      summary: gettokencache
      operationId: gettokencache
      responses:
        '200':
          description: ''
  /clone-68baa/v1/oauth/authenticate:
    post:
      summary: '(clone)copy_gcdm authenticate '
      operationId: 68baa8718ff295adbd2b8b54
      responses:
        '200':
          description: ''
  /log1:
    get:
      summary: log1
      operationId: log1
      responses:
        '200':
          description: ''
  /x:
    get:
      summary: backendX
      operationId: backendx
      responses:
        '200':
          description: ''
  /getcache:
    get:
      summary: getcache
      operationId: getcache
      responses:
        '200':
          description: ''
  /cachetest:
    get:
      summary: cahcetest
      operationId: cahcetest
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]